# Docker Compose file para MongoDB e Mongo Express
version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - 27017:27017  
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:mongoadmin@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    name: mongo-compose-network  
    driver: bridge      
